# -*- coding: utf-8 -*-
# pyuic5 -o ui_formhi0.py FormHell0.ui  --LP
# generate ui_formhi0 py file. UI defined in QT creator
# Form implementation generated from reading ui file 'FormHell0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormHello(object):
    def setupUi(self, FormHello):
        FormHello.setObjectName("FormHello")
        FormHello.resize(283, 156)
        self.labHello = QtWidgets.QLabel(FormHello)
        self.labHello.setGeometry(QtCore.QRect(50, 40, 189, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labHello.setFont(font)
        self.labHello.setObjectName("labHello")
        self.btnClose = QtWidgets.QPushButton(FormHello)
        self.btnClose.setGeometry(QtCore.QRect(100, 90, 75, 23))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(FormHello)
        QtCore.QMetaObject.connectSlotsByName(FormHello)

    def retranslateUi(self, FormHello):
        _translate = QtCore.QCoreApplication.translate
        FormHello.setWindowTitle(_translate("FormHello", "Demo2_2"))
        self.labHello.setText(_translate("FormHello", "你好啊 UI设计"))
        self.btnClose.setText(_translate("FormHello", "关闭"))
